export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT"; 
export const INCREMENT_FIVE = "INCREMENT_FIVE";
export const DECREMENT_FIVE = "DECREMENT_FIVE";
export const SAVE_BANNERS = 'SAVE_BANNERS';
export const SAVE_RECOMMENDS = "SAVE_RECOMMENDS"
export const FETCH_HOME_MULTIDATA = "FETCH_HOME_MULTIDATA"